export const genres = ['Sci-Fi', 'Drama', 'Thriller', 'Action', 'Fantasy', 'Mystery']

export const countryFlags = {
  France: '🇫🇷', Germany: '🇩🇪', UK: '🇬🇧',
  USA: '🇺🇸', Spain: '🇪🇸', Italy: '🇮🇹', Japan: '🇯🇵',
  Korea: '🇰🇷', Brazil: '🇧🇷', Canada: '🇨🇦', Australia: '🇦🇺',
  Mexico: '🇲🇽', Argentina: '🇦🇷', Sweden: '🇸🇪', Netherlands: '🇳🇱',
}

// Sorted alphabetically by lastName
export const users = [
  { firstName: "Noah",       lastName: "Anderson",     country: "USA"         },
  { firstName: "Hannah",     lastName: "Becker",       country: "Germany"     },
  { firstName: "Hugo",       lastName: "Bernard",      country: "France"      },
  { firstName: "Ava",        lastName: "Brown",        country: "USA"         },
  { firstName: "Alex",       lastName: "Carter",       country: "USA"         },
  { firstName: "Mia",        lastName: "Chen",         country: "Japan"       },
  { firstName: "Benjamin",   lastName: "Clark",        country: "USA"         },
  { firstName: "Giulia",     lastName: "Conti",        country: "Italy"       },
  { firstName: "Mason",      lastName: "Davis",        country: "USA"         },
  { firstName: "John",       lastName: "Doe",          country: "France"      },
  { firstName: "Lucas",      lastName: "Dubois",       country: "France"      },
  { firstName: "Astrid",     lastName: "Eriksson",     country: "Sweden"      },
  { firstName: "Marco",      lastName: "Esposito",     country: "Italy"       },
  { firstName: "Aurora",     lastName: "Ferrari",      country: "Italy"       },
  { firstName: "Carmen",     lastName: "Flores",       country: "Spain"       },
  { firstName: "Léa",        lastName: "Fontaine",     country: "France"      },
  { firstName: "Nao",        lastName: "Fujita",       country: "Japan"       },
  { firstName: "Luna",       lastName: "García",       country: "Spain"       },
  { firstName: "Richard",    lastName: "Gascan",       country: "UK"          },
  { firstName: "Liam",       lastName: "Harris",       country: "Canada"      },
  { firstName: "Diego",      lastName: "Hernández",    country: "Spain"       },
  { firstName: "Lisa",       lastName: "Hoffmann",     country: "Germany"     },
  { firstName: "Takeshi",    lastName: "Ito",          country: "Japan"       },
  { firstName: "Min",        lastName: "Jae Park",     country: "Korea"       },
  { firstName: "Ethan",      lastName: "Johnson",      country: "USA"         },
  { firstName: "Hana",       lastName: "Kimura",       country: "Japan"       },
  { firstName: "William",    lastName: "King",         country: "USA"         },
  { firstName: "Grace",      lastName: "Lee",          country: "Korea"       },
  { firstName: "Ingrid",     lastName: "Lindqvist",    country: "Sweden"      },
  { firstName: "Camila",     lastName: "López",        country: "Mexico"      },
  { firstName: "Roberto",    lastName: "Mancini",      country: "Italy"       },
  { firstName: "Chloé",      lastName: "Martin",       country: "France"      },
  { firstName: "Sofia",      lastName: "Martinez",     country: "Spain"       },
  { firstName: "Charlotte",  lastName: "Moore",        country: "UK"          },
  { firstName: "Silvia",     lastName: "Moretti",      country: "Italy"       },
  { firstName: "Elena",      lastName: "Müller",       country: "Germany"     },
  { firstName: "Hiroshi",    lastName: "Nakamura",     country: "Japan"       },
  { firstName: "Carlos",     lastName: "Pereira",      country: "Brazil"      },
  { firstName: "Pablo",      lastName: "Ramírez",      country: "Spain"       },
  { firstName: "Alessandro", lastName: "Ricci",        country: "Italy"       },
  { firstName: "Luca",       lastName: "Romani",       country: "Italy"       },
  { firstName: "Isabella",   lastName: "Rossi",        country: "Italy"       },
  { firstName: "Valentina",  lastName: "Sánchez",      country: "Argentina"   },
  { firstName: "Oliver",     lastName: "Schmidt",      country: "Germany"     },
  { firstName: "Max",        lastName: "Schulz",       country: "Germany"     },
  { firstName: "Rafael",     lastName: "Souza",        country: "Brazil"      },
  { firstName: "Yuki",       lastName: "Tanaka",       country: "Japan"       },
  { firstName: "James",      lastName: "Taylor",       country: "UK"          },
  { firstName: "Amelia",     lastName: "Thompson",     country: "Australia"   },
  { firstName: "Andrés",     lastName: "Torres",       country: "Mexico"      },
  { firstName: "Pieter",     lastName: "Van Den Berg", country: "Netherlands" },
  { firstName: "Felix",      lastName: "Wagner",       country: "Germany"     },
  { firstName: "Kenji",      lastName: "Watanabe",     country: "Japan"       },
  { firstName: "Sophie",     lastName: "White",        country: "UK"          },
  { firstName: "Emma",       lastName: "Wilson",       country: "UK"          },
  { firstName: "Sakura",     lastName: "Yamamoto",     country: "Japan"       },
  { firstName: "Marie",      lastName: "Zanzibar",     country: "Germany"     },
]

// Sorted alphabetically by title (ignoring leading "The" / "A" / "An")
export const movies = [
  { name: "1917",                                       year: "2019" },
  { name: "2001: A Space Odyssey",                      year: "1968" },
  { name: "Aftersun",                                   year: "2022" },
  { name: "Anatomy of a Fall",                          year: "2023" },
  { name: "Apocalypse Now",                             year: "1979" },
  { name: "Arrival",                                    year: "2016" },
  { name: "The Banshees of Inisherin",                  year: "2022" },
  { name: "Black Swan",                                 year: "2010" },
  { name: "Blade Runner 2049",                          year: "2017" },
  { name: "The Dark Knight",                            year: "2008" },
  { name: "Dune",                                       year: "2021" },
  { name: "Dune: Part Two",                             year: "2024" },
  { name: "Eternal Sunshine of the Spotless Mind",      year: "2004" },
  { name: "Everything Everywhere All at Once",          year: "2022" },
  { name: "Fight Club",                                 year: "1999" },
  { name: "Forrest Gump",                               year: "1994" },
  { name: "Get Out",                                    year: "2017" },
  { name: "The Godfather",                              year: "1972" },
  { name: "Gone Girl",                                  year: "2014" },
  { name: "Goodfellas",                                 year: "1990" },
  { name: "The Grand Budapest Hotel",                   year: "2014" },
  { name: "Gravity",                                    year: "2013" },
  { name: "Her",                                        year: "2013" },
  { name: "Hereditary",                                 year: "2018" },
  { name: "Inception",                                  year: "2010" },
  { name: "Interstellar",                               year: "2014" },
  { name: "Joker",                                      year: "2019" },
  { name: "Killers of the Flower Moon",                 year: "2023" },
  { name: "La La Land",                                 year: "2016" },
  { name: "The Lighthouse",                             year: "2019" },
  { name: "Mad Max: Fury Road",                         year: "2015" },
  { name: "The Matrix",                                 year: "1999" },
  { name: "Midsommar",                                  year: "2019" },
  { name: "Moonlight",                                  year: "2016" },
  { name: "No Country for Old Men",                     year: "2007" },
  { name: "Oppenheimer",                                year: "2023" },
  { name: "Parasite",                                   year: "2019" },
  { name: "Past Lives",                                 year: "2023" },
  { name: "Poor Things",                                year: "2023" },
  { name: "Portrait of a Lady on Fire",                 year: "2019" },
  { name: "Priscilla",                                  year: "2023" },
  { name: "Pulp Fiction",                               year: "1994" },
  { name: "A Quiet Place",                              year: "2018" },
  { name: "The Revenant",                               year: "2015" },
  { name: "Saving Private Ryan",                        year: "1998" },
  { name: "Schindler's List",                           year: "1993" },
  { name: "The Shawshank Redemption",                   year: "1994" },
  { name: "The Silence of the Lambs",                   year: "1991" },
  { name: "The Social Network",                         year: "2010" },
  { name: "Spirited Away",                              year: "2001" },
  { name: "Tenet",                                      year: "2020" },
  { name: "There Will Be Blood",                        year: "2007" },
  { name: "Uncut Gems",                                 year: "2019" },
  { name: "Whiplash",                                   year: "2014" },
  { name: "Your Name",                                  year: "2016" },
  { name: "The Zone of Interest",                       year: "2023" },
]
